server:
  port: 8080
spring:
  datasource:
    name: taptapanalysis
    url: jdbc:mysql://121.41.224.229:3306/taptapanalysis?serverTimezone=UTC
    username: root
    password: mySQL123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /templates/
      suffix: .html
    static-path-pattern: /static/**

mybatis:
  type-aliases-package: com.taptap.demo.entity
  mapper-locations: classpath:mapper/*.xml

